name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with: { version: 9 }

      - run: pnpm install --frozen-lockfile

      # ────────── LINT ──────────
      - run: pnpm -r lint

      # ────────── TESTS ─────────
      - run: pnpm -r test
        env:
          CI: "true"

      # ────────── BUILD ----─────
      - run: pnpm --filter @project2048/web build
