name: CI

on:
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with: { version: 9 }

      - run: pnpm install --frozen-lockfile

      - run: pnpm -r lint
      - run: pnpm -r test
